+ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Fri Jan  6 11:10:06 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL nmap
+ pkgs=nmap
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs nmap --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpwmro489c
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpwmro489c
+ DNF_INSTALL nmap 2
+ pkgs=nmap
+ node=2
+ '[' -z /tmp/tmpwmro489c ']'
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs nmap --node 2 --tempfile /tmp/tmpwmro489c
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 176, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
  File "/root/GitRepo/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.9/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.9/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
+ tmpfile2=
+ '[' -z /tmp/tmpwmro489c ']'
+ sudo systemctl start firewalld
Failed to start firewalld.service: Unit firewalld.service not found.
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Fri Jan  6 11:11:06 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Fri Jan  6 11:11:07 2023 - INFO  - Start executing testcase.
+ SLEEP_WAIT 1
+ wait_time=1
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/sleep_wait.py --time 1 --cmd '' --mode 1
+ nc -l -p 5060
+ sudo firewall-cmd --get-log-denied
+ grep off
sudo: firewall-cmd: command not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_firewalld_log_denied.sh line 35'
+ message='oe_test_firewalld_log_denied.sh line 35'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_firewalld_log_denied.sh line 35'
Fri Jan  6 11:11:12 2023 - ERROR - oe_test_firewalld_log_denied.sh line 35
+ return 0
+ sudo firewall-cmd --set-log-denied=all
+ grep success
sudo: firewall-cmd: command not found
+ sudo firewall-cmd --get-log-denied
+ grep all
sudo: firewall-cmd: command not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_firewalld_log_denied.sh line 38'
+ message='oe_test_firewalld_log_denied.sh line 38'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_firewalld_log_denied.sh line 38'
Fri Jan  6 11:11:14 2023 - ERROR - oe_test_firewalld_log_denied.sh line 38
+ return 0
+ SLEEP_WAIT 1
+ wait_time=1
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/sleep_wait.py --time 1 --cmd '' --mode 1
+ SSH_CMD 'echo test | nc 127.0.0.1 5060' '' '' ''
+ cmd='echo test | nc 127.0.0.1 5060'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/GitRepo/mugen-riscv/libs/locallibs/sshcmd.sh -c 'echo test | nc 127.0.0.1 5060' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Fri Jan  6 11:11:18 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 1
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log=
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep DST=127.0.0.1 /var/log/messages
+ grep DPT=5060
grep: /var/log/messages: No such file or directory
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_firewalld_log_denied.sh line 44'
+ message='oe_test_firewalld_log_denied.sh line 44'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_firewalld_log_denied.sh line 44'
Fri Jan  6 11:11:24 2023 - ERROR - oe_test_firewalld_log_denied.sh line 44
+ return 0
+ LOG_INFO 'Finish testcase execution.'
+ message='Finish testcase execution.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish testcase execution.'
Fri Jan  6 11:11:25 2023 - INFO  - Finish testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Jan  6 11:11:25 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Jan  6 11:11:26 2023 - INFO  - start environment cleanup.
+ sudo firewall-cmd --set-log-denied=off
sudo: firewall-cmd: command not found
++ pgrep -f 'nc -l -p 5060'
+ kill -9 2308
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpwmro489c ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpwmro489c
/root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh: line 97:  2308 Killed                  nc -l -p 5060 2>&1
+ '[' 0 -ne 0 ']'
+ DNF_REMOVE 2 nmap
+ node=2
+ pkg_list=nmap
+ mode=0
+ [[ -z /tmp/tmpwmro489c ]]
+ '[' 0 -ne 0 ']'
+ '[' 2 == 0 ']'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 2 --pkgs nmap --tempfile /tmp/tmpwmro489c
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 142, in rpm_remove
    conn = ssh_cmd.pssh_conn(
  File "/root/GitRepo/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.9/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.9/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Fri Jan  6 11:11:46 2023 - INFO  - Finish environment cleanup!
