+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Feb 14 02:15:12 2023 - INFO  - Start to run test.
+ service auditd restart
oe_test_audit_count_number_of_event.sh: line 25: service: command not found
+ CHECK_RESULT 127 0 0 'start failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='start failed'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'start failed'
+ LOG_ERROR 'start failed'
+ message='start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'start failed'
Tue Feb 14 02:15:14 2023 - ERROR - start failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_count_number_of_event.sh line 26'
+ message='oe_test_audit_count_number_of_event.sh line 26'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_count_number_of_event.sh line 26'
Tue Feb 14 02:15:16 2023 - ERROR - oe_test_audit_count_number_of_event.sh line 26
+ return 0
+ grep 'Event Summary Report'
+ aureport -e -i --summary
oe_test_audit_count_number_of_event.sh: line 27: aureport: command not found
+ CHECK_RESULT 1 0 0 'grep failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep failed'
+ LOG_ERROR 'grep failed'
+ message='grep failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'grep failed'
Tue Feb 14 02:15:18 2023 - ERROR - grep failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_count_number_of_event.sh line 28'
+ message='oe_test_audit_count_number_of_event.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_count_number_of_event.sh line 28'
Tue Feb 14 02:15:20 2023 - ERROR - oe_test_audit_count_number_of_event.sh line 28
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Feb 14 02:15:22 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Feb 14 02:15:24 2023 - ERROR - failed to execute the case.
+ exit 2
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_audit_count_number_of_event.sh post_test'
+ message='oe_test_audit_count_number_of_event.sh post_test'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'oe_test_audit_count_number_of_event.sh post_test'
Tue Feb 14 02:15:26 2023 - INFO  - oe_test_audit_count_number_of_event.sh post_test
